### ISSUE TITLE
Tizen.Net.Tv breaking application

### ISSUE THREAD

**Issue by yauhenipakala** [SamsungDForum/Xamarin.DRMPlayer#1]
Hi everyone!

This sample has wrong  NuGet package [Tizen.NET.TV 4.4.0.1341](https://www.nuget.org/packages/Tizen.NET.TV/4.4.0.1341) after installation he breaks Tizen application with `Segmentation fault`.
![VS exception](https://user-images.githubusercontent.com/766193/39911730-14d8e58e-5505-11e8-8b55-1c5f79dc596d.PNG)
```
This debug engine does not support exception conditions. The condition(s) will be ignored.
Loaded '[vdso]'. Cannot find or open the symbol file.
Loaded 'linux-gate.so.1'. Cannot find or open the symbol file.
Loaded 'JIT(0x81de5aa0)'. Cannot find or open the symbol file.
Loaded 'JIT(0x81df5148)'. Cannot find or open the symbol file.
Loaded 'JIT(0x81e213e0)'. Cannot find or open the symbol file.
Loaded 'JIT(0x81e059b8)'. Cannot find or open the symbol file.
Loaded 'JIT(0x81e13748)'. Cannot find or open the symbol file.
Loaded 'JIT(0x81e1c930)'. Cannot find or open the symbol file.
Loaded 'JIT(0x81e11fd8)'. Cannot find or open the symbol file.
Loaded 'JIT(0x81e1f7a8)'. Cannot find or open the symbol file.
Loaded 'JIT(0x81e102c8)'. Cannot find or open the symbol file.
Loaded 'JIT(0x81e110a0)'. Cannot find or open the symbol file.
Segmentation fault
```

Do you have any other ideas or workaround for use player with PlayReady?

**Comment by fryette** [comment]
The same issue

**Comment by heesong-kim** [comment]
@wcoder, Did you run the app with F5? How about with "Ctrl+F5"? I think it is needed to check whether this is a debugging issue or not. And which do you use? Emulator or TV? Please let me know the emulator version or TV model name also. Plus, you can get the official tech support from seller office.
http://seller.samsungapps.com/tv
https://developer.samsung.com/tv/distribute/seller-office/support/11-qa

**Comment by fryette** [comment]
@heesong-kim 
I used together with @wcoder emulator(latest version, Emulator manager 2.5.78)
We tried to run the following official sample: https://github.com/SamsungDForum/Xamarin.DRMPlayer
Also we tried to do it with clean project - result the same issue reproduced.
Issue reproduced in both configurations: debug and release.

**Comment by heesong-kim** [comment]
@fryette
Oh.. unfortunately, Xamarin.DRMPlayer is not working on emulator. It can not be launched on emulator.
Xamarin.DRMPlayer uses Tizen.TV.Multimedia and Tizen.TV.Multimedia is not supported on the emulator: https://developer.samsung.com/tv/tizen-net-tv/api-references
So, it probably threw NotSupportedException.

**Comment by fryette** [comment]
Oh, really?
So, seems we cannot develop on emulators, thus we need real devices....a lot...it's a pity

**Comment by fryette** [comment]
Do you know which models of TV support Tizen 4.0?

**Comment by heesong-kim** [comment]
@fryette Sorry.. this is a difficult question for me to answer directly.
Please use seller office.
http://seller.samsungapps.com/tv
https://developer.samsung.com/tv/distribute/seller-office/support/11-qa
You will be able to get the official answer about model.

**Comment by heesong-kim** [comment]
@fryette I think you can refer to https://developer.samsung.com/tv/develop/specifications/tv-model-groups/

**Comment by fryette** [comment]
@heesong-kim , Thank you very much!
